### ISSUE TITLE
Padding / margin issue on 2.0 RC17

### ISSUE THREAD

**Issue by dnish** [OnsenUI/react-onsenui#108]
Hey,
after upgrading from RC15 to RC17 all pages of my app got a wrong padding / margin. Some content is hidden behind the title bar on Android. It happens on every page with a title bar. Are there any changes (f.e. a new content wrapper) between RC15 and RC17?

**Comment by dnish** [comment]
Nope, I'm using it without renderToolbar. I'll check later if it fixes the issue.

**Comment by philolo1** [comment]
@dnish Since one of the early versions we used `renderToolbar`, you can look in the tutorials. We forgot to update some documents. Because of some changes in the core I believe now you have to use renderToolbar, since its put in some position of the DOM that is not exposed. 

I am closing the issue right now, but if it does not work for it, feel free to open it again.
