### ISSUE TITLE
[question] router

### ISSUE THREAD

**Issue by shprink** [OnsenUI/react-onsenui#63]
Hello guys,

I want to have a side menu with links to pages and I want to disable the link of the current page (to avoid being able to re push the same page several times).

For instance I click HOME LINK => goes to HOME page => disable HOME LINK

As the router events do not return the Route but only the Page (DOM) I was wondering how to do this.

Thanks,
Julien

**Comment by philolo1** [comment]
@shprink thanks for reporting. We also have the community https://community.onsen.io/ where you might has questions instead of creating issues.
I am not 100% sure i understand the question. What do you mean with `router` events, the navigator or the side menu? In the click function of the link in the side menu you could save in a global store or in the state which page you marked and adjust the onClick function to do nothing in this case, but maybe i am misunderstanding.

**Comment by shprink** [comment]
if there is an easy way to do the same as here http://m.julienrenaux.fr/

when you switch from HOME to AUTHORS for instance the AUTHOR menu item is disabled. it also works with the back button. if you go to another page ans come back it will be disabled.

In order to do that I had to store the current `route` (setRoute function) on the `renderPage` callback (navigator):

```
renderPage = (route, navigator) => {
    this.props.setRoute(route.id)
  }
```

 and create a custom back button (`renderPage` not being called when using `BackButton`) to also register the previous `route` as the current:

```
goBack = () => {
    const { navigator, setRoute } = this.props
    const pageToPop = navigator.pages[navigator.pages.length - 2]
    navigator.popPage().then(() => setRoute(pageToPop.props.id))
  }
```

I thought I could simplify that using navigators events `onPostPush` and `onPostPop` but `route` is not included in the event only the page is.

You can check how I resolved that use case => https://github.com/shprink/react-redux-onsenui-webpack-boilerplate

Hopefully there is a better way. thanks

**Comment by philolo1** [comment]
@shprink i think we can provide the route in the events, i want to hear @argelius opinion about it, so we can probably get back to you on Monday about it.

**Comment by argelius** [comment]
@shprink @philolo1 Sorry for the late reply. Have been busy with newborn children. :)

I also agree that we can provide the route in the events.

**Comment by shprink** [comment]
ho yeah that's right! Congrats!

The `route` is necessary in order to apply some restriction logic, so it would be great to have.

Let me know when you have a roadmap on that.

thanks very much.

**Comment by GoaGit** [comment]
Hello @philolo1, @shprink, since this thread is about routing I am posting this question here. Let's say that I have an with a side-menu. It is a tree structure; there is no shortcut from a lower level menu item (e.g. Item 1.1) to another lower level item (e.g. Item 2.1) from a different Menu. 

I am not making use of Redux by the way. In the App component I initialise the routing for the Root component. I am wondering which construct I should use to render the appropriate page given a click on a menu item (e.g. Menu item 2). Do you have any suggestions for me?

Menu structure:
```
MenuRoot
 |- Menu item 1
		|- Item 1.1
		|- Item 1.2
		|- ...
 |- Menu item 2
		|- Item 2.1
		|- Item 2.2
		|- ...
 |- ...
```
Code  for the Appcomponent (top-level component), the entry-point for the side-menu code:

```
...

// App component
<Navigator
	renderPage={ this.renderPage }
	initialRoute={ { component: MenuRootPage, key: 'MENUROOT' } }
/>

...
```

The UI component for the side menu:
```
...

const menuData = [ 
	{ index: 1, title: "Menu item 1", component: "M1", icon: ... }, 
	{ index: 2, title: "Menu item 2", component: "M2", icon: ... },
	{ index: 3, title: "Menu item 3", component: "M3", icon: ... },
	{ index: 4, title: "Menu item 4", component: "M4", icon: ... }
]; 

...
	
<List
	dataSource={ menuData  }
	renderHeader={ () => <ListHeader>Menu</ListHeader> }
	renderRow={ ( data ) => {
			return <ListItem 
					key={ `menuItem-${data.index}` } 
					modifier='longdivider' 
					tappable >
					<Icon
						icon={ data.icon } 
						size="50px" 
						fixed-width="true"
					/>
					{ `${data.title}` }
				</ListItem>
			}
		}
	/>
```
